### ISSUE TITLE
Gage Watershed TauDEM535 installer

### ISSUE THREAD

**Issue by JPollyGIS** [dtarb/TauDEM#119]
Running tool within QGIS environment. Tool runs, however output watershed grid is never consistently created the same way. Pour point "shapefile" contains "ID" field with unique id's set for each location. Flow direction "tif" has been created from the tau tools. resulting watershed grid appears to contain values of contributing area to each pour point. Theses values and delineation are never the same if the tool is ran twice with the same pour point and FDR inputs. Seems like a potential bug? any help would be appreciated.

**Comment by dtarb** [comment]
Try use the latest version of TauDEM (5.3.7 or code that is in 5.3.8).  I believe that this problem was fixed with the merge of some gage watershed fixes that were after version 5.3.5 but before version 5.3.7 (https://github.com/dtarb/TauDEM/pull/87/files)

**Comment by JPollyGIS** [comment]
Installed 5.3.7 from:
TauDEM 5.3.7 Complete Windows installer 
http://hydrology.usu.edu/taudem/taudem5/index.html

Tried testing on two different machines. I added a zip file of input testing data:
flow direction (tiff) and gauges file (shp). 
[TauDEM_testing_MultiGaugeDelination.zip](https://github.com/dtarb/TauDEM/files/855740/TauDEM_testing_MultiGaugeDelination.zip)

Still getting, inconsistent outputs.

**Comment by JPollyGIS** [comment]
Believe the issue I have been facing is related to how QGIS is calling TauDEM tools. My workaround, If I write a simple Python script to call mpiexec and GageWatershed the results are perfect. 

Using a subprocess.call function. 
subprocess.call(cmd, shell=False)

Hope it might help someone else down the road. Also, the TauDEM tools work fine via ESRI.

**Comment by pkdash** [comment]
Glad to know that it is working for you now. Thanks for this update.
